homework22

diff --git a/.github/workflows/flake8.yaml b/.github/workflows/flake8.yaml
--- a/.github/workflows/flake8.yaml
+++ b/.github/workflows/flake8.yaml
@@ -11,16 +11,34 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+
       - name: Set up Python 3.11
         uses: actions/setup-python@v3
         with:
           python-version: 3.11
+
+      - name: Create virtual environment
+        run: python -m venv venv
+
       - name: Install Dependencies
         run: |
+          source venv/bin/activate
           python -m pip install --upgrade pip
           pip install flake8
+
+      - name: Check for __init__.py files
+        run: |
+          missing_files=$(find . -type d ! -path "./venv/*" ! -path "./myenv/*" ! -path "*/__pycache__/*" ! -path "./.pytest_cache/*" -exec bash -c 'test -f "{}/__init__.py" || echo "{}/__init__.py"' \;)
+          if [ -n "$missing_files" ]; then
+            echo "Creating missing __init__.py files:"
+            echo "$missing_files" | while read -r file; do
+              echo "Creating $file"
+              touch "$file"
+            done
+          fi
+
       - name: Analysing the code with flake8
         run: |
-          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=myenv
-          flake8 . --count --max-complexity=10 --max-line-length=100 --statistics --exclude=myenv
-
+          source venv/bin/activate
+          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=myenv,venv
+          flake8 . --count --max-complexity=10 --max-line-length=100 --statistics --exclude=myenv,venv
